### ISSUE TITLE
Mobile browser support?

### ISSUE THREAD

**Issue by davidnormo** [vissense/vissense#16]
Hi there,

I see there is good desktop support, what about mobile browsers?

Thanks!

**Comment by theborakompanioni** [comment]
The script uses standard ES5 features - so every browser implementing ES5 should be covered. There is a "polyfill" for the VisibilityAPI (see supporting browser on [canisuse](http://caniuse.com/#search=hidden)) which will always report the page as visible on browsers not supporting it.

However, I have not checked every browser manually. The script itself is included on a quite a few websites with very high traffic so it runs on thousands of devices. Hence I am confident that most mobile browsers are also covered.

The demos with draggable elements do not work properly on mobile devices (I have created an [issue](https://github.com/vissense/vissense-demo/issues/3)) - but you can still verify it is working by scrolling around. 

Again, I have not checked different mobile browsers and I'd be happy if you report back when you are experiencing inconsistencies.

**Comment by theborakompanioni** [comment]
@davidnormo I have created a branch sauce/mobile-browser which will perform all tests on android and ios via saucelabs. (I suppose the default system browser is used). The problem with saucelabs its unreliability. Sometimes the builds run through without any issues - other times it will timeout on every vm execution..

I think it's better than nothing so I can live with it. Maybe it's because of their concurrent execution limits and I have to remove more Browser/OS combinations in favour of mobile browsers.. we'll see. 

So I will keep this issue open till I can provide proper reporting for mobile browsers. 
Nonetheless, I'd appreciate a short report about your experiences.

**Comment by davidnormo** [comment]
I've not used vissence at all. I was going to use a part of the code to check if an element is currently visible but it was specific for mobile devices. I probably won't have the time to help, sorry about that!

**Comment by theborakompanioni** [comment]
No problem at all, you already helped by opening issues/asking questions. Thanks!

**Comment by theborakompanioni** [comment]
Mobile browser have been added to automatic saucelabs tests and reports (129d235). The demo page is now a little bit more mobile friendly (example element is still not draggable though -> separate issue). Verified proper functioning on all tested devices. Hence, I am closing this issue.
