### ISSUE TITLE
Difficulties

### ISSUE THREAD

**Issue by WideCircle** [vissense/vissense#39]
Hi!
I'm having a lot of difficulties using this library...
I don't know what I'm doing wrong.

**1.** You can't use this library with getElementsByClassName?
Whenever I do I get "Uncaught Error: not an element node".

**2.** When I'm on a page that doesn't contain the selector I get the same error...also when using getElementById. Do I have to make sure to monitor only on the page that contain the ID I want to check for visibility?

This is my code:
```
var systemSymbols = document.getElementById('st-logo');

var visibility_monitor = VisSense.VisMon.Builder(VisSense(systemSymbols))
.on('fullyvisible', function() {
console.log ('inView');
visibility_monitor.stop(); // Stop monitor when become visible 
})
.on('hidden', function() {
console.log ('outView'); 
})
.build();

visibility_monitor.start();
```

Best, Niklas

**Comment by theborakompanioni** [comment]
@WideCircle Hey there. That's totally expected behaviour. 

1. `getElementsByClassName` returns a `HTMLCollection` object -> You can iterate over the collection and create a monitor for each element. e.g.:
```javascript
var myElements = document.getElementsByClassName("my-class");
for (var i = 0; i < myElements.length; i++) {
  VisSense.VisMon.Builder(VisSense(myElements[i]))
    .on('fullyvisible', function(monitor) {
      console.log ('inView');
      monitor.stop(); // Stop monitor when become visible 
    })
    .on('hidden', function() {
      console.log ('outView'); 
    })
    .build()
    .start();
}
```

2. If the element is not present in the DOM.. and you want to monitor it.. what do you expect to happen? The library just fails early and tries to state the problem. If the element is not present -> don't start the monitor:
```javascript
var systemSymbols = document.getElementById('st-logo');
if (systemSymbols) {
  // ... you code
}
```

Please report if that solves your problem. Thank you and have a nice day.

**Comment by WideCircle** [comment]
Ah - I see!!
Thank you very much for your fast answer...
I'm kind of new to javascript so this is a great explanation for me.
Thanks.

Best, Niklas

**Comment by theborakompanioni** [comment]
@WideCircle Glad to be of service. Happy coding!
