### ISSUE TITLE
Enable server side rendering

### ISSUE THREAD

**Issue by joseVFernandez** [vissense/vissense#41]
To enable the use of the library on universal javascript apps

**Comment by theborakompanioni** [comment]
@joseVFernandez thanks for your input. this was planned long ago but I never got the chance to implement it and it will not be work on in the foreseeable future :/

i will leave the issue open for a certain period of time for now..
so maybe people with the same needs are willing to create a pull requst.

thank you.

**Comment by joseVFernandez** [comment]
Hi @theborakompanioni, thanks so much for taking the time to look over this. 

I would love to take a crack at it or collaborate to work on the PR. 

If you have any pointers on where to start or hints that can pave the way would be extremely appreciated

**Comment by theborakompanioni** [comment]
@joseVFernandez Nice! I have looked into some commits as I already experimented with "jsdom" to enable such functionality as you can see in commit [#815e5ad](https://github.com/vissense/vissense/commit/815e5ad23f06c5c9a0e917080385b46ec97229f6). This has been in 2015, so maybe there is already a better solution - I removed it again because it did not work for all use cases (as far as i remember).
Also, in [this branch](https://github.com/vissense/vissense/tree/es6) i tried to port it all to webpack and es6 - which is not quite finished yet. Maybe this is the branch to work on.. what do you think?

I'd be glad to support you whenever you have any question.

Happy coding!
